FROM node:22.16.0-alpine

# Add git.
RUN apk add --no-cache git

# Add python because of the i18n-check script
RUN apk add python3

# Set the working directory in the container.
WORKDIR /app

# Source is not copied because it is mounted as a volume

# Nuxt 3 default port is 3000.
# Does not actually expose the port but documents it.
EXPOSE 3000
