FROM node:22.16.0-alpine AS builder

# Add git.
RUN apk add --no-cache git

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json (if available).
COPY ./frontend/package*.json ./

# Install project dependencies.
RUN npm install

# Copy the rest of the application source code into the container.
COPY ./frontend /app
COPY ./backend/schema.json /app/schema.json

# Get static graphql schema
ARG CODEGEN_SCHEMA
ENV CODEGEN_SCHEMA=${CODEGEN_SCHEMA}

# Run codegen
RUN npm run codegen-prod

# Make sure the API URL is available at generate time
ARG NUXT_PUBLIC_API_URL
ENV NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}

# Make sure the SAML URL is available at generate time
ARG NUXT_PUBLIC_SAML_URL
ENV NUXT_PUBLIC_SAML_URL=${NUXT_PUBLIC_SAML_URL}

# Build the application in production mode.
RUN npm run generate

# Create a new stage for the production image.
FROM nginx:alpine

# Copy built application files from the builder stage into the NGINX server that will server them.
COPY --from=builder /app/.output/public /usr/share/nginx/html

# Copy the NGINX configuration file into the container.
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port for the NGINX server.
# Does not actually expose the port but documents it.
EXPOSE 3000