FROM node:22.16.0-alpine

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json (if available).
COPY package*.json ./

# Install project dependencies
RUN npm install

# Nuxt 3 default port is 3000.
# Does not actually expose the port but documents it.
EXPOSE 3000
