services:
  postgres:
    image: postgres:15
    container_name: mr-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: 'psql -c "\l" postgres postgres'
      start_period: 5s
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/create_db.sql:/docker-entrypoint-initdb.d/myresearch.sql

  nginx-dev:
    image: nginx:latest
    container_name: mr-nginx-dev
    hostname: mr-nginx
    restart: unless-stopped
    profiles: ["dev"]
    depends_on:
      - django-dev
    volumes:
      - ./nginx.conf.dev:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:80"

  nginx-prod:
    image: nginx:latest
    container_name: mr-nginx-prod
    hostname: mr-nginx
    restart: unless-stopped
    profiles: ["prod"]
    depends_on:
      - django-prod
    volumes:
      - ./nginx.conf.prod:/etc/nginx/nginx.conf:ro
      - basta:/var/www/backend_static
    ports:
      - "5000:80"

  django-dev:
    image: mr-django
    container_name: mr-django-dev
    hostname: mr-django
    depends_on:
      postgres:
        condition: service_healthy
    restart: no
    profiles: ["dev"]
    build:
      context: ./backend
    healthcheck:
      test: "curl -f localhost:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - bapyca:/usr/src/app/backend/__pycache__
    expose:
      - "8000"
    command: sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 'mr-postgres'
      DJANGO_SETTINGS_MODULE: "myresearch.settings.dev"

  django-prod:
    image: mr-django
    container_name: mr-django-prod
    hostname: mr-django
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["prod"]
    build:
      context: ./backend
    healthcheck:
      test: "curl -f localhost/backend/:8000"
    volumes:
      - basta:/var/www/backend-static/
    expose:
      - "8000"
    command: sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000
      "
    environment:
      DB_HOST: 'mr-postgres'
      DJANGO_SETTINGS_MODULE: "myresearch.settings.prod"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}

  vue-dev:
    image: mr-vue-dev
    container_name: mr-vue-dev
    hostname: mr-vue
    restart: no
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      # Enable live-reloading of frontend code.
      - ./frontend:/app
      # Use container's node_modules.
      - frontend-node-modules:/app/node_modules
    environment:
      # Allows Nuxt to be accessible from the outside.
      - HOST=0.0.0.0

  vue-prod:
    image: mr-vue-prod
    container_name: mr-vue-prod
    hostname: mr-vue
    restart: unless-stopped
    profiles: ["prod"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

volumes:
  frontend-node-modules:
  pgdata:
  bapyca:
  basta:

networks:
    my-research:
      driver: bridge
