services:
  postgres:
    image: postgres:15
    container_name: mr-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: 'psql -c "\l" postgres postgres'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/create_db.sql:/docker-entrypoint-initdb.d/myresearch.sql

  nginx:
    image: nginx:latest
    container_name: mr-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:80"

  django-dev:
    image: mr-django-dev
    container_name: mr-django
    depends_on:
      postgres:
        condition: service_healthy
    restart: no
    build:
      context: ./backend
      dockerfile: Dockerfile
    healthcheck:
      test: "curl -f localhost:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - bapyca:/usr/src/app/backend/__pycache__
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 'mr-postgres'

  vue-dev:
    image: mr-vue-dev
    container_name: mr-vue
    restart: no
    profiles: ["dev"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      # Enable live-reloading of frontend code.
      - ./frontend:/app
      # Use container's node_modules.
      - frontend-node-modules:/app/node_modules
    environment:
      # Allows Nuxt to be accessible from the outside.
      - HOST=0.0.0.0

  vue-prod:
    image: mr-vue-prod
    container_name: mr-vue
    restart: unless-stopped
    profiles: ["prod"]
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

volumes:
  frontend-node-modules:
  pgdata:
  bapyca:

networks:
    my-research:
      driver: bridge
