# Generated by Django 5.0.14 on 2025-09-30 07:45

from django.db import migrations

from unittest.mock import patch

# Custom migration to load fixtures for group model
# the fixtures here are dumps from the state of the group from the time
# of implementation. They were made using from a version of the db that already had these fixtures
# The command used to make the dumps:
# python manage.py dumpdata auth.group --format=jsonl

group_fixtures = """
{"model": "auth.group","pk": 1,"fields": {"name": "Privacy officer","permissions": []}}
{"model": "auth.group","pk": 2,"fields": {"name": "FETC member","permissions": []}}
"""

def load_registration_fixtures(apps, schema_editor):
    from django.core.serializers import deserialize

    # We must patch the apps manager from the Python deserializer
    # module with the historical manager we receive as an argument
    # to this migration action.
    # This prevents this migration from breaking as a result of future
    # changes to the Group models.
    with patch(
        "django.core.serializers.python.apps",
        apps,
    ):
        for obj in deserialize("jsonl", group_fixtures):
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_registration_fixtures, migrations.RunPython.noop),
    ]
