# Generated by Django 5.0.14 on 2025-09-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("text_en", models.CharField(max_length=200, null=True)),
                ("text_nl", models.CharField(max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Context about the question and its purpose, which will be shown to the user.",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Context about the question and its purpose, which will be shown to the user.",
                        null=True,
                    ),
                ),
                (
                    "description_nl",
                    models.TextField(
                        blank=True,
                        help_text="Context about the question and its purpose, which will be shown to the user.",
                        null=True,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DateQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("future_only", models.BooleanField(default=False)),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="FileUploadQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("size_limit", models.PositiveIntegerField()),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="NumberQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("positive_only", models.BooleanField(default=False)),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="SelectQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                (
                    "multiple",
                    models.BooleanField(
                        default=False,
                        help_text="Allows multiple options to be selected if true.",
                    ),
                ),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="TextQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "placeholder_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "placeholder_nl",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("lines", models.PositiveIntegerField(default=1)),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("default_value", models.BooleanField(default=False)),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="MRForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_nl", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("version", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the URL.", max_length=200, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subforms",
                        to="form.mrform",
                    ),
                ),
            ],
            options={
                "order_with_respect_to": "parent",
            },
        ),
        migrations.CreateModel(
            name="FormInfoText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_nl", models.TextField(null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_texts",
                        to="form.mrform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormInfoQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("text_en", models.CharField(max_length=200, null=True)),
                ("text_nl", models.CharField(max_length=200, null=True)),
                ("link", models.URLField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_questions",
                        to="form.mrform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basequestion",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="form.mrform",
            ),
        ),
        migrations.CreateModel(
            name="SelectOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("label_en", models.CharField(max_length=200, null=True)),
                ("label_nl", models.CharField(max_length=200, null=True)),
                ("default_selected", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="form.selectquestion",
                    ),
                ),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name="basequestion",
            order_with_respect_to="form",
        ),
    ]
