# Generated by Django 5.0.14 on 2025-12-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mrform",
            options={"verbose_name": "Form", "verbose_name_plural": "Forms"},
        ),
        migrations.CreateModel(
            name="QuestionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("show", "Show target"),
                            ("hide", "Hide target"),
                            ("repeat", "Repeat target a fixed number of times"),
                            ("repeat_dynamic", "Repeat based on answer value"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_value",
                    models.JSONField(),
                ),
                ("repeat_count", models.PositiveIntegerField(blank=True, null=True)),
                ("use_answer_as_count", models.BooleanField(default=False)),
                (
                    "target_question",
                    models.ForeignKey(
                        help_text="The question that this condition applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="form.basequestion",
                    ),
                ),
                (
                    "trigger_question",
                    models.ForeignKey(
                        help_text="The question whose answer triggers this condition.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_conditions",
                        to="form.basequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("show", "Show target"),
                            ("hide", "Hide target"),
                            ("repeat", "Repeat target a fixed number of times"),
                            ("repeat_dynamic", "Repeat based on answer value"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_value",
                    models.JSONField(),
                ),
                ("repeat_count", models.PositiveIntegerField(blank=True, null=True)),
                ("use_answer_as_count", models.BooleanField(default=False)),
                (
                    "target_step",
                    models.ForeignKey(
                        help_text="The step that this condition applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="form.step",
                    ),
                ),
                (
                    "trigger_question",
                    models.ForeignKey(
                        help_text="The question whose answer triggers this condition.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_step_conditions",
                        to="form.basequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.mrform"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField()),
                (
                    "repeat_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Index for repeated questions."
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.basequestion",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="form.userformsubmission",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="questioncondition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("condition_type__in", ["repeat", "repeat_dynamic"]),
                        _negated=True,
                    ),
                    ("repeat_count__isnull", False),
                    ("use_answer_as_count", True),
                    _connector="OR",
                ),
                name="repeat_requires_count_or_dynamic_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepcondition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("condition_type__in", ["repeat", "repeat_dynamic"]),
                        _negated=True,
                    ),
                    ("repeat_count__isnull", False),
                    ("use_answer_as_count", True),
                    _connector="OR",
                ),
                name="repeat_requires_count_or_dynamic_step",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionresponse",
            unique_together={("submission", "question", "repeat_index")},
        ),
    ]
