# Generated by Django 5.0.14 on 2026-01-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_alter_mrform_options_questioncondition_stepcondition_and_more"),
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userformsubmission",
            name="study",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="research.study",
            ),
        ),
    ]
