# Generated by Django 5.0.14 on 2026-02-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_userformsubmission_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioncondition",
            name="trigger_question",
            field=models.ForeignKey(
                help_text="The question whose answer triggers this condition.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_%(class)s",
                to="form.basequestion",
            ),
        ),
        migrations.AlterField(
            model_name="stepcondition",
            name="trigger_question",
            field=models.ForeignKey(
                help_text="The question whose answer triggers this condition.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_%(class)s",
                to="form.basequestion",
            ),
        ),
    ]
