# Generated by Django 5.0.14 on 2026-02-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_userformsubmission_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrform",
            name="study_name_question",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the answer to this question will be used as the study name.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_name_forms",
                to="form.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="mrform",
            name="version",
            field=models.CharField(
                default=1, help_text="E.g. 1.0.0, 2.15.3", max_length=10
            ),
            preserve_default=False,
        ),
    ]
