# Generated by Django 5.0.14 on 2026-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_userformsubmission_study"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionresponse",
            unique_together={("question", "repeat_index")},
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="submissions",
            field=models.ManyToManyField(
                related_name="responses", to="form.userformsubmission"
            ),
        ),
        migrations.RemoveField(
            model_name="questionresponse",
            name="submission",
        ),
    ]
