# Generated by Django 5.0.14 on 2026-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_alter_questioncondition_trigger_question_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="submissions",
            field=models.ManyToManyField(
                related_name="responses", to="form.userformsubmission"
            ),
        ),
        migrations.RemoveField(
            model_name="questionresponse",
            name="submission",
        ),
    ]
