# Generated by Django 5.0.14 on 2026-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0005_alter_questionresponse_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioncondition",
            name="trigger_value",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="stepcondition",
            name="trigger_value",
            field=models.JSONField(blank=True),
        ),
    ]
