# Generated by Django 5.0.14 on 2026-03-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0006_alter_questioncondition_trigger_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepinfotext",
            name="step",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_text",
                to="form.step",
            ),
        ),
        migrations.DeleteModel(
            name="StepInfoQuestion",
        ),
    ]
