# Generated by Django 5.0.14 on 2026-03-18 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0006_alter_questioncondition_trigger_value_and_more"),
        ("research", "0003_remove_reviewround_reviewed_form_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mrform",
            name="study_name_question",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, the answer to this question will be used as the study name.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_name_forms",
                to="form.basequestion",
            ),
        ),
        migrations.AddField(
            model_name="mrform",
            name="version",
            field=models.CharField(
                default="0.0.0", help_text="E.g. 1.0.0, 2.15.3", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userformsubmission",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="form.mrform",
            ),
        ),
        migrations.AlterField(
            model_name="userformsubmission",
            name="study",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="research.study",
            ),
        ),
        migrations.AlterField(
            model_name="userformsubmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
