# Generated by Django 5.0.14 on 2026-03-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_mrform_study_name_question_mrform_version_and_more"),
        ("research", "0003_remove_reviewround_reviewed_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userformsubmission",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="research.study",
            ),
        ),
    ]
