# Generated by Django 5.0.14 on 2026-04-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_mrform_study_name_question_mrform_version_and_more"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="selectoption",
            order_with_respect_to="question",
        ),
    ]
