# Generated by Django 5.0.14 on 2026-04-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_mrform_study_name_question_mrform_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="is_overview",
            field=models.BooleanField(
                default=False,
                help_text="If true, this step serves as an overview step for the entire form. It should not have any questions attached to it.",
            ),
        ),
    ]
