# Generated by Django 5.0.14 on 2026-04-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_mrform_study_name_question_mrform_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="select_options",
                to="form.selectquestion",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="selectoption",
            order_with_respect_to="question",
        ),
    ]
