# Generated by Django 5.0.14 on 2026-04-13 10:17

import form.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_mrform_study_name_question_mrform_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="slug",
            field=models.SlugField(
                help_text="Used in the URL.",
                max_length=200,
                unique=True,
                validators=[form.validators.validate_slug_not_overview],
            ),
        ),
    ]
