# Generated by Django 5.0.14 on 2026-04-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0009_alter_selectoption_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="form.selectquestion",
            ),
        ),
    ]
