# Generated by Django 5.0.14 on 2026-04-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0010_step_is_overview"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="selectoption",
            order_with_respect_to="question",
        ),
    ]
