# Generated by Django 5.0.14 on 2026-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0011_alter_selectoption_order_with_respect_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="textquestion",
            name="is_email",
            field=models.BooleanField(default=False),
        ),
    ]
