# Generated by Django 5.0.14 on 2026-05-20 14:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0011_alter_selectoption_order_with_respect_to"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="step",
            name="step_parent_xor_form",
        ),
        migrations.AddField(
            model_name="basequestion",
            name="annotation_key",
            field=models.CharField(
                blank=True,
                help_text="<strong>Only for important questions! When in doubt, leave this blank!</strong> If needed, provide a short, descriptive name in snake_case, eg. 'recording_details'",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only snake_case is allowed (e.g. 'recording_details'). Read help text carefully!",
                        regex="^[a-z]+(_[a-z]+)*$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="basequestion",
            name="form",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_questions",
                to="form.mrform",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="top_form",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_steps",
                to="form.mrform",
            ),
        ),
        migrations.AddConstraint(
            model_name="basequestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("annotation_key__isnull", False)),
                fields=("form", "annotation_key"),
                name="unique_annotation_key_per_form",
            ),
        ),
    ]
