# Generated by Django 5.0.14 on 2026-06-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0012_remove_step_step_parent_xor_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basequestion",
            name="form",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="form.mrform",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="form.mrform",
            ),
        ),
    ]
