# Generated by Django 5.0.14 on 2026-07-01 11:50

import cdh.files.db.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_auto_20210921_1014"),
        ("form", "0013_alter_basequestion_form_alter_step_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileuploadquestion",
            name="size_limit",
            field=models.PositiveIntegerField(help_text="Maximum file size in bytes."),
        ),
        migrations.CreateModel(
            name="MRDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cdh.files.db.fields.FileField(
                        filename_generator=cdh.files.db.fields._default_filename_generator,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
