# Generated by Django 5.0.14 on 2026-06-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0013_alter_basequestion_form_alter_step_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repeatable",
            fields=[
                ("repeat_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="RepeatableStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="form.step",
                    ),
                ),
                (
                    "repeatable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.repeatable",
                    ),
                ),
            ],
            bases=("form.repeatable", "form.step"),
        ),
        migrations.CreateModel(
            name="RepeatIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="form.repeatindex",
                    ),
                ),
                (
                    "submissions",
                    models.ManyToManyField(
                        related_name="repeats", to="form.userformsubmission"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repeatable",
            name="repeat_indices",
            field=models.ManyToManyField(default=None, to="form.repeatindex"),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="repeat_index",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form.repeatindex",
            ),
        ),
    ]
