# Generated by Django 5.0.14 on 2026-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0013_alter_basequestion_form_alter_step_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="textquestion",
            name="is_email",
            field=models.BooleanField(default=False),
        ),
    ]
