# Generated by Django 5.0.14 on 2026-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0014_alter_fileuploadquestion_size_limit_mrdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="textquestion",
            name="is_email",
            field=models.BooleanField(default=False),
        ),
    ]
