# Generated by Django 5.0.14 on 2026-07-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0015_textquestion_is_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepinfotext",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stepinfotext",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="stepinfotext",
            name="content_nl",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="stepinfotext",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_info_texts",
                to="form.step",
            ),
        ),
        migrations.AlterField(
            model_name="stepinfotext",
            name="text",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="stepinfotext",
            name="text_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="stepinfotext",
            name="text_nl",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name="stepinfotext",
            order_with_respect_to="step",
        ),
    ]
