# Generated by Django 5.0.14 on 2026-07-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0015_textquestion_is_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("text_en", models.CharField(max_length=200, null=True)),
                ("text_nl", models.CharField(max_length=200, null=True)),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_nl", models.TextField(null=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_infos",
                        to="form.step",
                    ),
                ),
            ],
            options={
                "order_with_respect_to": "step",
            },
        ),
        migrations.DeleteModel(
            name="StepInfoText",
        ),
    ]
