# Generated by Django 5.0.14 on 2026-07-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0015_textquestion_is_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=200)),
                ("header_en", models.CharField(max_length=200, null=True)),
                ("header_nl", models.CharField(max_length=200, null=True)),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_nl", models.TextField(null=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="form.step",
                    ),
                ),
            ],
        ),
    ]
