# Generated by Django 5.0.14 on 2026-07-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0016_stepinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stepinfo",
            old_name="text",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="stepinfo",
            old_name="text_en",
            new_name="content_en",
        ),
        migrations.RenameField(
            model_name="stepinfo",
            old_name="text_nl",
            new_name="content_nl",
        ),
    ]
