# Generated by Django 5.0.14 on 2026-08-03 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0016_repeatable_repeatablestep_repeatindex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatableTextQuestion",
            fields=[
                (
                    "textquestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="form.textquestion",
                    ),
                ),
                (
                    "repeatable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.repeatable",
                    ),
                ),
            ],
            bases=("form.repeatable", "form.textquestion"),
        ),
    ]
