# Generated by Django 5.0.14 on 2026-08-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0016_stepinfotext_content_stepinfotext_content_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repeatable",
            fields=[
                ("repeat_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="RepeatableStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="form.step",
                    ),
                ),
                (
                    "repeatable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.repeatable",
                    ),
                ),
            ],
            bases=("form.repeatable", "form.step"),
        ),
        migrations.CreateModel(
            name="RepeatableTextQuestion",
            fields=[
                (
                    "textquestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="form.textquestion",
                    ),
                ),
                (
                    "repeatable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.repeatable",
                    ),
                ),
            ],
            bases=("form.repeatable", "form.textquestion"),
        ),
        migrations.CreateModel(
            name="RepeatIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="form.repeatindex",
                    ),
                ),
                (
                    "submissions",
                    models.ManyToManyField(
                        related_name="repeats", to="form.userformsubmission"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repeatable",
            name="repeat_indices",
            field=models.ManyToManyField(default=None, to="form.repeatindex"),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="repeat_index",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form.repeatindex",
            ),
        ),
        migrations.CreateModel(
            name="RepeatableStepQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("create_text", models.CharField()),
                ("create_text_en", models.CharField(null=True)),
                ("create_text_nl", models.CharField(null=True)),
                ("none_yet_text", models.CharField()),
                ("none_yet_text_en", models.CharField(null=True)),
                ("none_yet_text_nl", models.CharField(null=True)),
                (
                    "repeatable_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.repeatablestep",
                    ),
                ),
            ],
            bases=("form.basequestion",),
        ),
    ]
