# Generated by Django 5.0.14 on 2026-07-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0016_stepinfo_delete_stepinfotext"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepInfoText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_text",
                        to="form.step",
                    ),
                ),
            ],
        ),
    ]
