# Generated by Django 5.0.14 on 2026-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0017_repeatable_repeatablestep_repeatabletextquestion_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="questioncondition",
            name="repeat_requires_count_or_dynamic_question",
        ),
        migrations.RemoveConstraint(
            model_name="stepcondition",
            name="repeat_requires_count_or_dynamic_step",
        ),
        migrations.RemoveField(
            model_name="questioncondition",
            name="repeat_count",
        ),
        migrations.RemoveField(
            model_name="questioncondition",
            name="use_answer_as_count",
        ),
        migrations.RemoveField(
            model_name="stepcondition",
            name="repeat_count",
        ),
        migrations.RemoveField(
            model_name="stepcondition",
            name="use_answer_as_count",
        ),
        migrations.AlterField(
            model_name="questioncondition",
            name="condition_type",
            field=models.CharField(
                choices=[("show", "Show target"), ("hide", "Hide target")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stepcondition",
            name="condition_type",
            field=models.CharField(
                choices=[("show", "Show target"), ("hide", "Hide target")],
                max_length=20,
            ),
        ),
    ]
