# Generated by Django 5.0.14 on 2026-08-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0017_repeatabletextquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatableStepQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("create_text", models.CharField()),
                ("create_text_en", models.CharField(null=True)),
                ("create_text_nl", models.CharField(null=True)),
                ("none_yet_text", models.CharField()),
                ("none_yet_text_en", models.CharField(null=True)),
                ("none_yet_text_nl", models.CharField(null=True)),
                (
                    "repeatable_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.repeatablestep",
                    ),
                ),
            ],
            bases=("form.basequestion",),
        ),
    ]
