# Generated by Django 5.0.14 on 2026-08-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0017_repeatabletextquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatableStepQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                (
                    "repeatable_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.repeatablestep",
                    ),
                ),
            ],
            bases=("form.basequestion",),
        ),
    ]
