# Generated by Django 5.0.14 on 2026-09-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0017_basequestion_step_name_override_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repeatable",
            fields=[
                ("repeat_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="RepeatableStepQuestion",
            fields=[
                (
                    "basequestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.basequestion",
                    ),
                ),
                ("create_text", models.CharField()),
                ("create_text_en", models.CharField(null=True)),
                ("create_text_nl", models.CharField(null=True)),
                ("none_yet_text", models.CharField()),
                ("none_yet_text_en", models.CharField(null=True)),
                ("none_yet_text_nl", models.CharField(null=True)),
            ],
            bases=("form.basequestion",),
        ),
        migrations.CreateModel(
            name="RepeatIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="questioncondition",
            name="repeat_requires_count_or_dynamic_question",
        ),
        migrations.RemoveConstraint(
            model_name="stepcondition",
            name="repeat_requires_count_or_dynamic_step",
        ),
        migrations.RemoveField(
            model_name="questioncondition",
            name="repeat_count",
        ),
        migrations.RemoveField(
            model_name="questioncondition",
            name="use_answer_as_count",
        ),
        migrations.RemoveField(
            model_name="stepcondition",
            name="repeat_count",
        ),
        migrations.RemoveField(
            model_name="stepcondition",
            name="use_answer_as_count",
        ),
        migrations.AlterField(
            model_name="questioncondition",
            name="condition_type",
            field=models.CharField(
                choices=[("show", "Show target"), ("hide", "Hide target")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stepcondition",
            name="condition_type",
            field=models.CharField(
                choices=[("show", "Show target"), ("hide", "Hide target")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RepeatableStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="form.step",
                    ),
                ),
                (
                    "repeatable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.repeatable",
                    ),
                ),
            ],
            bases=("form.repeatable", "form.step"),
        ),
        migrations.CreateModel(
            name="RepeatableTextQuestion",
            fields=[
                (
                    "textquestion_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="form.textquestion",
                    ),
                ),
                (
                    "repeatable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="form.repeatable",
                    ),
                ),
            ],
            bases=("form.repeatable", "form.textquestion"),
        ),
        migrations.AddField(
            model_name="repeatindex",
            name="parent",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="form.repeatindex",
            ),
        ),
        migrations.AddField(
            model_name="repeatindex",
            name="submissions",
            field=models.ManyToManyField(
                related_name="repeats", to="form.userformsubmission"
            ),
        ),
        migrations.AddField(
            model_name="repeatable",
            name="repeat_indices",
            field=models.ManyToManyField(default=None, to="form.repeatindex"),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="repeat_index",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form.repeatindex",
            ),
        ),
        migrations.AddField(
            model_name="repeatablestepquestion",
            name="repeatable_step",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="form.repeatablestep"
            ),
        ),
    ]
