# Generated by Django 5.0.14 on 2026-07-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0017_rename_text_stepinfo_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stepinfo",
            old_name="header",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="stepinfo",
            old_name="header_en",
            new_name="text_en",
        ),
        migrations.RenameField(
            model_name="stepinfo",
            old_name="header_nl",
            new_name="text_nl",
        ),
    ]
