# Generated by Django 5.0.14 on 2026-10-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0018_repeatable_repeatablestepquestion_repeatindex_and_more"),
    ]

    operations = []
