# Generated by Django 5.0.14 on 2026-07-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0018_rename_header_stepinfo_text_and_more"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="stepinfo",
            order_with_respect_to="step",
        ),
    ]
