# Generated by Django 5.0.14 on 2026-09-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0019_basequestion_step_name_override_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basequestion",
            name="step_name_override",
            field=models.BooleanField(
                default=False,
                help_text="If this is set to True, the answer to the question will override the name of its step (for display purposes). It can only be true for one question per step.",
            ),
        ),
    ]
