# Generated by Django 5.0.14 on 2026-07-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0019_alter_stepinfo_order_with_respect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepinfo",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_infos",
                to="form.step",
            ),
        ),
    ]
