# Generated by Django 5.0.14 on 2026-07-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0020_alter_stepinfo_step"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StepInfoText",
        ),
    ]
