# Generated by Django 5.0.14 on 2026-03-18 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_reviewround_review_statuschange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewround",
            name="reviewed_form",
        ),
        migrations.RemoveField(
            model_name="statuschange",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="statuschange",
            name="study",
        ),
        migrations.RemoveField(
            model_name="study",
            name="title",
        ),
        migrations.AddField(
            model_name="study",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewRound",
        ),
        migrations.DeleteModel(
            name="StatusChange",
        ),
    ]
