# Generated by Django 5.0.14 on 2026-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_reviewround_review_statuschange"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="study",
            name="reference",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
