# Generated by Django 5.0.14 on 2026-02-17 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_mrform_study_name_question_mrform_version"),
        ("research", "0002_reviewround_review_statuschange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewround",
            name="reviewed_form",
        ),
        migrations.RemoveField(
            model_name="statuschange",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="statuschange",
            name="study",
        ),
        migrations.RemoveField(
            model_name="study",
            name="title",
        ),
        migrations.AddField(
            model_name="study",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="study",
            name="form",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="form.mrform"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewRound",
        ),
        migrations.DeleteModel(
            name="StatusChange",
        ),
    ]
