# Generated by Django 5.0.14 on 2026-04-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0004_reviewround_review_statuschange"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"verbose_name_plural": "Studies"},
        ),
    ]
