# Generated by Django 5.0.14 on 2026-04-14 08:16

from django.db import migrations, models

def generate_references(apps, schema_editor):
    # Run save for all studies to generate ref numbers
    Study = apps.get_model("research", "Study")
    for study in Study.objects.all():
        Study.save()

def reverse_func(apss, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_alter_study_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
        # First add the reference field with null=True
        migrations.AddField(
            model_name="study",
            name="reference",
            field=models.CharField(max_length=10, unique=True, null=True),
            preserve_default=False,
        ),
        # Generate references for all studies
        migrations.RunPython(generate_references, reverse_func),
        # Remove null=True
        migrations.AlterField(
            model_name='study',
            name='reference',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
