# Generated by Django 5.0.14 on 2026-04-14 08:16

from django.db import migrations, models


def generate_references(apps, schema_editor):
    # Generate ref num's for all pre-existing studies using the same logic as
    # Study.save()
    # Note: This should never happen in production
    from django.utils import timezone
    from django.db import transaction

    Study = apps.get_model("research", "Study")
    YearCounter = apps.get_model("research", "YearCounter")

    for study in Study.objects.all():
        if not study.reference:
            with transaction.atomic():
                year = timezone.now().year % 100

                counter_obj, _ = YearCounter.objects.select_for_update().get_or_create(
                    year=year
                )

                counter_obj.counter += 1
                counter_obj.save()

                study.reference = f"MR-{year:02d}-{counter_obj.counter:04d}"
                study.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_alter_study_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("counter", models.IntegerField(default=0)),
            ],
        ),
        # First add the reference field with null=True
        migrations.AddField(
            model_name="study",
            name="reference",
            field=models.CharField(max_length=10, unique=True, null=True),
            preserve_default=False,
        ),
        # Generate references for all studies
        migrations.RunPython(generate_references, reverse_func),
        # Remove null=True
        migrations.AlterField(
            model_name="study",
            name="reference",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
