# Generated by Django 5.0.14 on 2026-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_yearcounter_study_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
