# Generated by Django 5.0.14 on 2026-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0006_yearcounter_study_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuschange",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ]
            ),
        ),
    ]
