# Generated by Django 5.0.14 on 2026-06-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_alter_statuschange_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="If true, the study is considered deleted and will not be shown in the UI.",
            ),
        ),
    ]
