# Generated by Django 5.0.14 on 2026-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_alter_statuschange_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
