# Generated by Django 5.0.14 on 2026-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0008_study_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
