# Generated by Django 5.0.14 on 2026-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Note title")),
                (
                    "title_en",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Note title"
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Note title"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="For links to other pages within the MR/grant-tool, format url like '/notes/1/'. For links, to other websites, format url like 'https://www.uu.nl'. In case of a really long word, that is overflowing the formatting, go into the source and add the bootstrap class 'text-break' to the paragraph in question.",
                        verbose_name="Note content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="For links to other pages within the MR/grant-tool, format url like '/notes/1/'. For links, to other websites, format url like 'https://www.uu.nl'. In case of a really long word, that is overflowing the formatting, go into the source and add the bootstrap class 'text-break' to the paragraph in question.",
                        null=True,
                        verbose_name="Note content",
                    ),
                ),
                (
                    "content_nl",
                    models.TextField(
                        help_text="For links to other pages within the MR/grant-tool, format url like '/notes/1/'. For links, to other websites, format url like 'https://www.uu.nl'. In case of a really long word, that is overflowing the formatting, go into the source and add the bootstrap class 'text-break' to the paragraph in question.",
                        null=True,
                        verbose_name="Note content",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Used in the URL, will be generated if not provided",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
