# Generated by Django 5.0.14 on 2026-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(
                help_text="For links to other pages within the MR, format url like '/notes/1/'. For links, to other websites, format url like 'https://www.uu.nl'. In case of a really long word, that is overflowing the formatting, go into the source and add the bootstrap class 'text-break' to the paragraph in question.",
                verbose_name="Note content",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content_en",
            field=models.TextField(
                help_text="For links to other pages within the MR, format url like '/notes/1/'. For links, to other websites, format url like 'https://www.uu.nl'. In case of a really long word, that is overflowing the formatting, go into the source and add the bootstrap class 'text-break' to the paragraph in question.",
                null=True,
                verbose_name="Note content",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="content_nl",
            field=models.TextField(
                help_text="For links to other pages within the MR, format url like '/notes/1/'. For links, to other websites, format url like 'https://www.uu.nl'. In case of a really long word, that is overflowing the formatting, go into the source and add the bootstrap class 'text-break' to the paragraph in question.",
                null=True,
                verbose_name="Note content",
            ),
        ),
    ]
