name: Run Django tests

on:
  pull_request:

jobs:
  django-tests:
    name: Build and test Django production container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Compose
        uses: docker/setup-compose-action@v1
      - name: Copy test environment
        run: |
          cp .env.example .env
      - name: Run Django tests
        run: |
          docker compose run django-prod python manage.py test
      - name: Check for missing migrations
        run: |
          docker compose run django-prod python manage.py makemigrations --dry-run --check