name: Run Django tests

on:
  pull_request:

jobs:
  django-tests:
    name: Build and test Django production container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Compose
        uses: docker/setup-compose-action@v1
      - name: Copy test environment and secrets
        run: |
          cp .env.example .env
          cp certificates/private.key secrets/
          cp certificates/public.cert secrets/
      - name: Build django-prod container
        run: docker compose build django-prod
      - name: Check for missing migrations
        run: docker compose run django-prod python manage.py makemigrations --dry-run --check
      - name: Check if schema.json is up to date
        run: |
          docker compose run django-dev python manage.py graphql_schema --out /tmp/schema.json
          diff backend/schema.json /tmp/schema.json
          diff frontend/schema.json /tmp/schema.json
      - name: Run Django tests
        run: docker compose run django-prod pytest
