name: Check GraphQL schema

on:
  pull_request:

jobs:
  check-schema:
    name: Check schema.json is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Compose
        uses: docker/setup-compose-action@v1
      - name: Copy test environment and secrets
        run: |
          cp .env.example .env
          cp certificates/private.key secrets/
          cp certificates/public.cert secrets/
      - name: Build django-dev container
        run: docker compose --profile dev build django-dev
      - name: Generate GraphQL schema
        run: docker compose --profile dev run django-dev python manage.py graphql_schema --out /usr/src/app/backend/schema_generated.json
      - name: Check backend/schema.json is up to date
        run: diff backend/schema.json backend/schema_generated.json
      - name: Check frontend/schema.json is up to date
        run: diff frontend/schema.json backend/schema_generated.json
      - name: Cleanup
        if: always()
        run: rm -f backend/schema_generated.json
